# Generated by Django 3.0.5 on 2020-04-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="nickname",),
        migrations.AddField(
            model_name="user",
            name="date_of_birthday",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "admin"), ("AUTHOR", "user")],
                default="AUTHOR",
                max_length=20,
            ),
        ),
    ]
