FROM python:3.8-stretch

LABEL maintainer="roman4hik"

ARG DJANGO_SETTINGS_MODULE
ARG DATABASE_URL
ARG DJANGO_DEBUG
ARG PROJECT_PATH

ENV PYTHONUNBUFFERED 1
ENV PROJECT_PATH ${PROJECT_PATH:-/app}
ENV PYTHONPATH ${PROJECT_PATH}
ENV LANG C.UTF-8
ENV LANGUAGE C.UTF-8
ENV LC_ALL C.UTF-8

COPY . ${PROJECT_PATH}
WORKDIR ${PROJECT_PATH}
